# -*- coding: utf-8 -*-
"""InsertionSort.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnfMbjMp8ztIa7ghkuFJtR1_wYxMIFDu
"""

def insertion_sort(arr):
    
    
    for i in range(1,len(arr)):
        
     
        currentvalue = arr[i]
        position = i
        
        
        while position>0 and arr[position-1]>currentvalue:
            
            arr[position]=arr[position-1]
            position = position-1

        arr[position]=currentvalue

arr =[3,5,4,6,8,1,2,12,41,25]
insertion_sort(arr)
arr

